Feature/jitsi
TableCo/react-native-sdk pull request #20
Opened 2020-11-18 09:01 UTC by AAfify1

Jitsi Implementation ready for testing

2020-11-18 09:54 UTC, gazreese requested changes

2020-11-18 09:54 UTC, gazreese commented on lib/JitsiVideo.js
> +    const url = `https://8x8.vc/${this.state.tenant}/${this.state.room}?jwt=${this.state.jwt}`;
Just in case we have to change it

2020-11-18 09:54 UTC, gazreese commented on lib/JitsiVideo.js
> +      email: this.state.user.email ? this.state.user.email : 'anon@test.com',
Maybe make it anon@email.com so that it doesn't look like test data? Or can we use '' and it still works?

2020-11-18 13:04 UTC, AAfify1 commented on lib/JitsiVideo.js
> +      email: this.state.user.email ? this.state.user.email : 'anon@test.com',
Ill double check that but should work

2020-11-30 08:40 UTC, gazreese approved these changes

2020-12-07 09:08 UTC, merged